api_platform:
    title: 'Symfony REST API, API PLATFORM'
    description: 'Projet API Symfony, mettant en avant un CRUD avec une entité'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
